domain_path: C:\Users\flavi\Desktop\SSC\PROIECT\newPlatform\proiect\export\proiect\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\vivado\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
